[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ayoayo"
version = "0.1.0"
description = "Ayoayo board game project"
dependencies = [
    "pygame>=2.6.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "pytest",
    "pytest-cov"
]
