from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from game_logic.Game import Game





# Tests generated by an LLM


def test_end_turn_appends_board_snapshot_and_switches_player():
    """Verifies that end_turn stores the current board state and advances turn parity."""
    game = Game()
    game.board.field_collection.fields[0].beans = 9
    game.board.bank[game.player_1] = 3

    game.end_turn()

    assert game.current_round() == 2
    assert game.current_player() is game.player_2
    assert len(game.board_history) == 2
    assert game.board_history[-1].field_collection.fields[0].beans == 9
    assert game.board_history[-1].bank[game.player_1] == 3


def test_undo_turn_restores_previous_board_snapshot():
    """Verifies that undo_turn reverts board and round back by one snapshot."""
    game = Game()

    game.board.field_collection.fields[0].beans = 7
    game.board.bank[game.player_1] = 1
    game.end_turn()

    game.board.field_collection.fields[0].beans = 2
    game.board.bank[game.player_1] = 9
    game.end_turn()

    game.undo_turn()

    assert game.current_round() == 2
    assert game.current_player() is game.player_2
    assert len(game.board_history) == 2
    assert game.board.field_collection.fields[0].beans == 7
    assert game.board.bank[game.player_1] == 1


def test_undo_turn_is_noop_in_first_round():
    """Verifies that undo_turn does nothing when no previous snapshot exists."""
    game = Game()
    initial_board = game.board.clone_deep()

    game.undo_turn()

    assert game.current_round() == 1
    assert len(game.board_history) == 1
    assert game.board.field_collection.fields[0].beans == initial_board.field_collection.fields[0].beans
    assert game.board.bank[game.player_1] == initial_board.bank[game.player_1]
    assert game.board.bank[game.player_2] == initial_board.bank[game.player_2]


def test_undo_turn_is_blocked_after_winner_is_set():
    """Verifies that undo_turn returns without changes once winner is set."""
    game = Game()
    game.board.field_collection.fields[0].beans = 8
    game.end_turn()

    game.board.field_collection.fields[0].beans = 1
    game.winner = game.player_1

    game.undo_turn()

    assert game.current_round() == 2
    assert len(game.board_history) == 2
    assert game.board.field_collection.fields[0].beans == 1
