from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from game_logic.Board import Board
from game_logic.Player import Player





# Tests generated by an LLM


def _create_board_with_custom_state() -> tuple[Board, Player, Player]:
    """Creates a board with a custom state for testing purposes."""
    player_1 = Player("Player 1")
    player_2 = Player("Player 2")
    board = Board(player_1, player_2)

    board.bank[player_1] = 9
    board.bank[player_2] = 4
    board.field_collection.fields[0].beans = 10
    board.field_collection.fields[5].beans = 1
    board.field_collection.fields[6].beans = 7
    board.field_collection.fields[11].beans = 2

    return board, player_1, player_2


def test_clone_deep_copies_full_board_state():
    """Verifies that clone_deep creates a new object with identical but independent data."""
    board, player_1, player_2 = _create_board_with_custom_state()

    clone = board.clone_deep()

    assert clone is not board
    assert clone.bank is not board.bank
    assert clone.bank[player_1] == board.bank[player_1]
    assert clone.bank[player_2] == board.bank[player_2]

    assert clone.field_collection is not board.field_collection
    for original_field, cloned_field in zip(
        board.field_collection.fields, clone.field_collection.fields
    ):
        assert cloned_field is not original_field
        assert cloned_field.beans == original_field.beans
        assert cloned_field.owner is original_field.owner


def test_clone_deep_isolated_from_original_mutations():
    """Verifies that mutating the original after cloning does not affect the clone."""
    board, player_1, player_2 = _create_board_with_custom_state()
    clone = board.clone_deep()

    board.bank[player_1] = 99
    board.field_collection.fields[0].beans = 42

    assert clone.bank[player_1] == 9
    assert clone.bank[player_2] == 4
    assert clone.field_collection.fields[0].beans == 10


def test_clone_deep_original_isolated_from_clone_mutations():
    """Verifies that mutating the clone after cloning does not affect the original."""
    board, player_1, player_2 = _create_board_with_custom_state()
    clone = board.clone_deep()

    clone.bank[player_2] = 77
    clone.field_collection.fields[6].beans = 13

    assert board.bank[player_1] == 9
    assert board.bank[player_2] == 4
    assert board.field_collection.fields[6].beans == 7
